### ISSUE TITLE
"Size of backlog" last point is really low

### ISSUE THREAD

**Issue by kelson42** [kiwix/metrics#24] opened 2020-01-15 15:49 UTC
I see no reason for that. Maybe it should just be removed

**Comment by florentk** [comment] 2020-01-15 19:46
duplicate with https://github.com/kiwix/metrics/issues/17

**Comment by florentk** [comment] 2020-01-17 14:59
The last value is good, when I zoom in, I have not the a bad last point. The problem is Kibiter/Kibana which bad extrapols when time range is high. You can also try "last 6 months", the last point is good.

**Comment by florentk** [comment] 2020-01-20 18:56
fixed via 5c26bae28f9b6e3ff733872e26a45138f47a86b3 and effc887

**Closed by florentk** 2020-01-20 18:56 UTC
Labels: bug
